// design/build-css.mjs — DTCG tokens -> site/src/styles/tokens.css.
//
// No Style Dictionary (design-system.md §9): one output target does not justify
// a build system. `:root` carries the primitives plus the LIGHT semantic tier;
// the dark blocks override the SEMANTIC TIER ONLY — primitives are never
// redefined (§5). `color-scheme: light dark` is declared so native controls,
// scrollbars and form widgets follow. Run: node design/build-css.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, 'design-tokens.json'), 'utf8'));
const out = join(here, '..', 'site', 'src', 'styles', 'tokens.css');

const flat = new Map(); // dotted path -> raw $value
(function walk(node, path) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$') || !value || typeof value !== 'object') continue;
    if ('$value' in value) flat.set([...path, key].join('.'), value.$value);
    else walk(value, [...path, key]);
  }
})(tokens, []);

const deref = (v) => (typeof v === 'string' ? v.replace(/\{([^}]+)\}/g, (_, r) => deref(flat.get(r))) : v);
const render = (v) =>
  Array.isArray(v) ? (typeof v[0] === 'number' ? `cubic-bezier(${v.join(', ')})`
    : v.map((f) => (/[^\w-]/.test(f) ? `"${f}"` : f)).join(', '))
  : v && typeof v === 'object' ? `${v.offsetX} ${v.offsetY} ${v.blur} ${v.spread} ${deref(v.color)}`
  : String(deref(v));

// theme.<mode>.action.hover -> --action-hover · component.panel.danger.bar-dark -> --panel-danger-bar
const name = (p) => '--' + p.replace(/^theme\.(light|dark)\./, '').replace(/^component\./, '')
  .replace(/[-.](light|dark)$/, '').replace(/\./g, '-');
const tier = (p) => /^theme\.dark\./.test(p) || /[-.]dark$/.test(p) ? 'dark'
  : /^theme\.light\./.test(p) || /[-.]light$/.test(p) ? 'light' : null;

const block = (want, indent) => [...flat].filter(([p]) => tier(p) === want)
  .map(([p, v]) => `${indent}${name(p)}: ${render(v)};`).join('\n');

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `/* GENERATED by design/build-css.mjs from design/design-tokens.json.
   Never hand-edit. Change the tokens, then re-run \`node design/build-css.mjs\`
   (\`make build-tokens\` re-solves the palette and re-verifies WCAG contrast).
   This is the ONLY file allowed to contain raw colour literals — see
   site/scripts/check-tokens.mjs. */
:root {
  color-scheme: light dark;
${block(null, '  ')}

${block('light', '  ')}
}

/* Semantic tier only. Primitives above are never redefined. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${block('dark', '    ')}
  }
}

:root[data-theme="dark"] {
${block('dark', '  ')}
}
`);
console.log(`design/build-css.mjs: ${flat.size} tokens -> ${out}`);
